### ISSUE TITLE
ACL related question

### ISSUE THREAD

**Issue by donovano** [spring-epfl/SSCred#1]
Hi, thanks for your interesting project. I had a couple questions, both concerning ACL:

You say: _“This credential is not linked to the identity of the user.”_ Is this true if the verifying entity is also the issuer? What I mean by this is, I understand that the issuer_pk can be distributed and a 3rd party can thus verify the credential and the identity is not given away, but is there something that the issuer can determine of the identity when it verifies it? Or is the issuer just as ‘blind’ to the identity as a third party verifier when verifying a credential?

My second question also relates to this area. You say: _“However, using a credential more than once is detectable and the verifier can link interactions with the same credential”_. I see in your code you throw an exception in show_credential if it is used twice. What is the point of using it twice anyway - your attributes and message are already tied up in the cred_private prior to calling this function and the result of calling it is just another credential for the same message and attributes as before. 

Donovan

**Comment by kasra-edalat** [comment]
Hi Donovan,

I'm glad that you find the project interesting :) 

The issuer does not have any advantage in verifying/identifying a credential. Knowing the issuer's public key is required for verifying a credential and knowing the issuer's secret key does not leak any information when verifying a credential. Moreover, the issuer does not learn any information about users' attributes and messages during the issuance phase to use this extra information for inferring more information about users from comparing their revealed attributes to a user database. Therefore, there are no privacy disadvantages in having the same party for both issuance and verification. 

ACL is designed to be single-use, so the functionality is limited if the user wants to misuse it by showing a credential multiple times. One common use case for ACL is blind authentication tokens where the user gets one credential with a fixed message and attributes per access to the system. For example, ACL can be used in a search engine that requires you to pay per search. The credential can contain "journal access" and "patent access" as attributes and the message will be "I have paid for one search". If the user shows the same credential for performing searches q1 and q2, then the search engine will learn that the same user has asked q1 and q2 beyond rejecting the second search. Besides showing the same credential multiple times, the user may want to reveal different subsets of attributes in two interactions, like first only searching for journal entries and second only searching for patents. The choice of which attribute you want to reveal is done when showing the credential. The reason for raising an exception when using a credential multiple times is to prevent the privacy damage of unintentional re-use. 

Kasra

**Comment by donovano** [comment]
Thanks Kasra, answer's good. Closing.
